name: Deploy via RV.com

on:
  workflow_call:
    inputs:
      build_path:
        required: true
        type: String

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: ${{ GITHUB_WORKSPACE }}/cross-channel-wartime
    - name: Use Node.js 19.6.0
      uses: actions/setup-node@v3
      with:
        node-version: 19.6.0
        cache: 'npm'
    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
    - uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('${{ GITHUB_WORKSPACE }}/cross-channel-wartime/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm ci
    - run: BUILD_PATH=${{ inputs.build_path }} npm run build
