name: Deploy via RV.com

on:
  workflow_call:
    outputs:
      ccw_artifact_name:
        description: "The name of the artifact"
        value: ${{ jobs.build.outputs.ccw_artifact_name }}


jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: ${{ steps.ccw_artifact_name.outputs.ccw_artifact_name }}
    steps:
    - uses: actions/checkout@v3
      with:
        repository: RyanVerhey/cross-channel-wartime
        ref: 'use-github-pages'
    - run: pwd
    - run: ls -la
    - name: Use Node.js 19.6.0
      uses: actions/setup-node@v3
      with:
        node-version: 19.6.0
        cache: 'npm'
    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
    - uses: actions/cache@v3
      id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: pwd
    - run: ls -la
    - run: npm ci
    - run: npm run build
    - id: ccw_artifact_name
      run: echo "ccw_artifact_name=ccw_artifact" >> $GITHUB_OUTPUT
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.ccw_artifact_name.outputs.ccw_artifact_name }}
        path: ./build
